image: swedishembedded/build:v0.24.5

default:
  tags:
    - docker

stages:
 - build

# This job builds applications
build:
    stage: build
    artifacts:
        paths:
        expire_in: 1 week
        when: always
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    script:
        # Empty for now since we test this in sdk
        - echo "Empty"
